Update

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,6 +9,11 @@ set -e
 # debug verbosely.
 #set -x
 
+echo "arg 0 = $0" # path to compile script e.g. /tmp/buildpacks/4ba03ce399e56995160747b832f5e464/bin/compile
+echo "arg 1 = $1" # build output directory e.g. /tmp/app
+echo "arg 2 = $2" # /tmp/cache
+echo "List of files in $1: `ls $1`" # .tar.gz
+
 # Load config vars into environment (from https://devcenter.heroku.com/articles/buildpack-api)
 export_env_dir() {
   env_dir=$1
@@ -56,13 +61,13 @@ fi
 
 # Try "$APP_SOURCE_DIR/app/" if meteor app isn't there (the "Iron scaffolding
 # tool" default).
-if [ ! -d "$APP_SOURCE_DIR/.meteor" ] && [ -d "$APP_SOURCE_DIR/app/.meteor" ]; then
-  APP_SOURCE_DIR="$APP_SOURCE_DIR/app/"
-fi
-if [ ! -d "$APP_SOURCE_DIR/.meteor" ]; then
-  echo "FATAL: Can't find meteor app. Set METEOR_APP_DIR to the relative location of the meteor app within your repository if it's not in the root or 'app/' subdirectory.  (Tried ${APP_SOURCE_DIR})"
-  exit 1
-fi
+# if [ ! -d "$APP_SOURCE_DIR/.meteor" ] && [ -d "$APP_SOURCE_DIR/app/.meteor" ]; then
+#   APP_SOURCE_DIR="$APP_SOURCE_DIR/app/"
+# fi
+# if [ ! -d "$APP_SOURCE_DIR/.meteor" ]; then
+#   echo "FATAL: Can't find meteor app. Set METEOR_APP_DIR to the relative location of the meteor app within your repository if it's not in the root or 'app/' subdirectory.  (Tried ${APP_SOURCE_DIR})"
+#   exit 1
+# fi
 
 # Where we will install meteor. Has to be outside the APP_CHECKOUT_DIR.
 METEOR_DIR="$CACHE_DIR/meteor"
@@ -157,9 +162,24 @@ if [ -z "$METEOR_NPM" ] || [ -z "$METEOR_NODE" ] ; then
   exit 1
 fi
 
-# Copy node into place for production.
-NODE="$COMPILE_DIR"/bin/node
-cp "$METEOR_NODE" "$NODE"
+if [ -n "${USE_METEOR_NODE+1}" ]; then
+  # Copy node into place for production.
+  NODE="$COMPILE_DIR"/bin/node
+  cp "$METEOR_NODE" "$NODE"
+else
+  NODE_VER_AVAILABLE=$(curl --silent --get https://semver.io/node/resolve/4.x.x)
+
+  # Download node from Heroku's S3 mirror of nodejs.org/dist
+  status "Downloading and installing node $NODE_VER_AVAILABLE"
+  NODE_INSTALLER=node-installer.tar.gz
+  NODE_URL="https://s3pository.heroku.com/node/v$NODE_VER_AVAILABLE/node-v$NODE_VER_AVAILABLE-linux-x64.tar.gz"
+  curl $NODE_URL > $NODE_INSTALLER
+  tar xzf $NODE_INSTALLER -C $BUILD_DIR
+
+  # Move node (and npm) into $NODE and make them executable
+  mv $BUILD_DIR/node-v$NODE_VER_AVAILABLE-linux-x64//bin/node $NODE
+fi
+
 chmod a+x "$NODE"
 
 # Add npm and node path so that 1.4's npm-rebuild.js will function.
@@ -174,7 +194,7 @@ if [ -e "$APP_SOURCE_DIR"/package.json ]; then
   $METEOR_NPM install
 fi
 
-# Related to https://github.com/meteor/meteor/issues/2796 and
+# Related to https://github.com/meteor/meteor/issues/2796 and 
 # https://github.com/meteor/meteor/issues/2606.  Some packages only build their
 # assets at runtime, and thus they are not available for bundling unless meteor
 # has been launched.  To opt-in to this, set BUILDPACK_PRELAUNCH_METEOR=1.
@@ -193,7 +213,30 @@ echo "-----> Building Meteor app with ROOT_URL: $ROOT_URL"
 BUNDLE_DEST=`mktemp -d "$BUILDPACK_DIR/build-XXXX"`
 
 # The actual invocation of `meteor build`!
-METEOR build $BUILD_OPTIONS --server $ROOT_URL $SERVER_ONLY_FLAG --directory $BUNDLE_DEST
+# METEOR build $BUILD_OPTIONS --server $ROOT_URL $SERVER_ONLY_FLAG --directory $BUNDLE_DEST
+
+
+# Extract app
+# echo "Present working directory: `pwd`" # /home/vcap
+# echo "List of files: `ls`" # app
+# echo "List of files in app: `ls app`"
+
+echo "APP_SOURCE_DIR = $APP_SOURCE_DIR" # /tmp/app/.meteor/heroku_build
+BUNDLE_DEST=`mktemp -d "$BUILDPACK_DIR/build-XXXX"`
+echo "BUNDLE_DEST = $BUNDLE_DEST" #  /tmp/buildpacks/4ba03ce399e56995160747b832f5e464/build-qKQH
+
+if [ -e $APP_SOURCE_DIR/*.gz ]; then
+for archive in $APP_SOURCE_DIR/*.gz; do
+  echo "archive: $archive"
+  tar -zxf $archive -C $BUNDLE_DEST
+  # rm $archive
+done
+# elif [ -e $COMPILE_DIR/bundle ]; then
+# mv $APP_CHECKOUT_DIR/bundle "$COMPILE_DIR/app"
+# else
+#  mv app/* $COMPILE_DIR/app
+fi
+
 
 echo "-----> Moving built slug to $COMPILE_DIR/app"
 mv $BUNDLE_DEST/bundle "$COMPILE_DIR/app"
